include ../deploy/Makefile

USERNAME=peng
PORT=6021
upload:
	#./upload.sh
	$(call upload, bin/)


#restart-frpc:
#	$(call upload, .config/systemd/user/frpc.service)
#	$(call command, "systemctl --user daemon-reload && \
#					systemctl --user restart frpc && \
#					systemctl --user status frpc | head")
#

