services:
  db-migration:
    container_name: infisical-db-migration
    image: infisical/infisical:latest-postgres
    env_file: .env
    command: npm run migration:latest
    pull_policy: always
    networks:
      - infisical

  backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      db-migration:
        condition: service_completed_successfully
    image: infisical/infisical:latest-postgres
    pull_policy: always
    env_file: .env
    ports:
      - xxxxxxxxxxx:8080
    environment:
      - NODE_ENV=production
    networks:
      - infisical
networks:
  infisical:
   