
bindAddr = "0.0.0.0"
bindPort = 7000
kcpBindPort = 7000
auth.method = "xxxxx"
auth.token = "xxx"


webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"
